//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("QLBanHangModel", "FK_CTHD_HoaDon", "HoaDon", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DTO.HoaDon), "CTHD", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DTO.CTHD), true)]
[assembly: EdmRelationshipAttribute("QLBanHangModel", "FK_CTHD_SanPham", "SanPham", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DTO.SanPham), "CTHD", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DTO.CTHD), true)]
[assembly: EdmRelationshipAttribute("QLBanHangModel", "FK_HoaDon_KhachHang", "KhachHang", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DTO.KhachHang), "HoaDon", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DTO.HoaDon), true)]
[assembly: EdmRelationshipAttribute("QLBanHangModel", "FK_HoaDon_Nhanvien", "Nhanvien", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DTO.Nhanvien), "HoaDon", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DTO.HoaDon), true)]
[assembly: EdmRelationshipAttribute("QLBanHangModel", "FK_SanPham_LoaiSP", "LoaiSP", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DTO.LoaiSP), "SanPham", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DTO.SanPham), true)]

#endregion

namespace DTO
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class QLBanHangEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new QLBanHangEntities object using the connection string found in the 'QLBanHangEntities' section of the application configuration file.
        /// </summary>
        public QLBanHangEntities() : base("name=QLBanHangEntities", "QLBanHangEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new QLBanHangEntities object.
        /// </summary>
        public QLBanHangEntities(string connectionString) : base(connectionString, "QLBanHangEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new QLBanHangEntities object.
        /// </summary>
        public QLBanHangEntities(EntityConnection connection) : base(connection, "QLBanHangEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CTHD> CTHDs
        {
            get
            {
                if ((_CTHDs == null))
                {
                    _CTHDs = base.CreateObjectSet<CTHD>("CTHDs");
                }
                return _CTHDs;
            }
        }
        private ObjectSet<CTHD> _CTHDs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<HoaDon> HoaDons
        {
            get
            {
                if ((_HoaDons == null))
                {
                    _HoaDons = base.CreateObjectSet<HoaDon>("HoaDons");
                }
                return _HoaDons;
            }
        }
        private ObjectSet<HoaDon> _HoaDons;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<KhachHang> KhachHangs
        {
            get
            {
                if ((_KhachHangs == null))
                {
                    _KhachHangs = base.CreateObjectSet<KhachHang>("KhachHangs");
                }
                return _KhachHangs;
            }
        }
        private ObjectSet<KhachHang> _KhachHangs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<LoaiSP> LoaiSPs
        {
            get
            {
                if ((_LoaiSPs == null))
                {
                    _LoaiSPs = base.CreateObjectSet<LoaiSP>("LoaiSPs");
                }
                return _LoaiSPs;
            }
        }
        private ObjectSet<LoaiSP> _LoaiSPs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Nhanvien> Nhanviens
        {
            get
            {
                if ((_Nhanviens == null))
                {
                    _Nhanviens = base.CreateObjectSet<Nhanvien>("Nhanviens");
                }
                return _Nhanviens;
            }
        }
        private ObjectSet<Nhanvien> _Nhanviens;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SanPham> SanPhams
        {
            get
            {
                if ((_SanPhams == null))
                {
                    _SanPhams = base.CreateObjectSet<SanPham>("SanPhams");
                }
                return _SanPhams;
            }
        }
        private ObjectSet<SanPham> _SanPhams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CTHDs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCTHDs(CTHD cTHD)
        {
            base.AddObject("CTHDs", cTHD);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the HoaDons EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToHoaDons(HoaDon hoaDon)
        {
            base.AddObject("HoaDons", hoaDon);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the KhachHangs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToKhachHangs(KhachHang khachHang)
        {
            base.AddObject("KhachHangs", khachHang);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the LoaiSPs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLoaiSPs(LoaiSP loaiSP)
        {
            base.AddObject("LoaiSPs", loaiSP);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Nhanviens EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNhanviens(Nhanvien nhanvien)
        {
            base.AddObject("Nhanviens", nhanvien);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SanPhams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSanPhams(SanPham sanPham)
        {
            base.AddObject("SanPhams", sanPham);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QLBanHangModel", Name="CTHD")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CTHD : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CTHD object.
        /// </summary>
        /// <param name="maHD">Initial value of the MaHD property.</param>
        /// <param name="maSP">Initial value of the MaSP property.</param>
        public static CTHD CreateCTHD(global::System.String maHD, global::System.String maSP)
        {
            CTHD cTHD = new CTHD();
            cTHD.MaHD = maHD;
            cTHD.MaSP = maSP;
            return cTHD;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MaHD
        {
            get
            {
                return _MaHD;
            }
            set
            {
                if (_MaHD != value)
                {
                    OnMaHDChanging(value);
                    ReportPropertyChanging("MaHD");
                    _MaHD = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MaHD");
                    OnMaHDChanged();
                }
            }
        }
        private global::System.String _MaHD;
        partial void OnMaHDChanging(global::System.String value);
        partial void OnMaHDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MaSP
        {
            get
            {
                return _MaSP;
            }
            set
            {
                if (_MaSP != value)
                {
                    OnMaSPChanging(value);
                    ReportPropertyChanging("MaSP");
                    _MaSP = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MaSP");
                    OnMaSPChanged();
                }
            }
        }
        private global::System.String _MaSP;
        partial void OnMaSPChanging(global::System.String value);
        partial void OnMaSPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> Soluong
        {
            get
            {
                return _Soluong;
            }
            set
            {
                OnSoluongChanging(value);
                ReportPropertyChanging("Soluong");
                _Soluong = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Soluong");
                OnSoluongChanged();
            }
        }
        private Nullable<global::System.Int16> _Soluong;
        partial void OnSoluongChanging(Nullable<global::System.Int16> value);
        partial void OnSoluongChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> Giamgia
        {
            get
            {
                return _Giamgia;
            }
            set
            {
                OnGiamgiaChanging(value);
                ReportPropertyChanging("Giamgia");
                _Giamgia = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Giamgia");
                OnGiamgiaChanged();
            }
        }
        private Nullable<global::System.Single> _Giamgia;
        partial void OnGiamgiaChanging(Nullable<global::System.Single> value);
        partial void OnGiamgiaChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QLBanHangModel", "FK_CTHD_HoaDon", "HoaDon")]
        public HoaDon HoaDon
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<HoaDon>("QLBanHangModel.FK_CTHD_HoaDon", "HoaDon").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<HoaDon>("QLBanHangModel.FK_CTHD_HoaDon", "HoaDon").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<HoaDon> HoaDonReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<HoaDon>("QLBanHangModel.FK_CTHD_HoaDon", "HoaDon");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<HoaDon>("QLBanHangModel.FK_CTHD_HoaDon", "HoaDon", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QLBanHangModel", "FK_CTHD_SanPham", "SanPham")]
        public SanPham SanPham
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SanPham>("QLBanHangModel.FK_CTHD_SanPham", "SanPham").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SanPham>("QLBanHangModel.FK_CTHD_SanPham", "SanPham").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SanPham> SanPhamReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SanPham>("QLBanHangModel.FK_CTHD_SanPham", "SanPham");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SanPham>("QLBanHangModel.FK_CTHD_SanPham", "SanPham", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QLBanHangModel", Name="HoaDon")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class HoaDon : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new HoaDon object.
        /// </summary>
        /// <param name="maHD">Initial value of the MaHD property.</param>
        /// <param name="ngayLapHD">Initial value of the NgayLapHD property.</param>
        /// <param name="ngayGiaoHang">Initial value of the NgayGiaoHang property.</param>
        public static HoaDon CreateHoaDon(global::System.String maHD, global::System.DateTime ngayLapHD, global::System.DateTime ngayGiaoHang)
        {
            HoaDon hoaDon = new HoaDon();
            hoaDon.MaHD = maHD;
            hoaDon.NgayLapHD = ngayLapHD;
            hoaDon.NgayGiaoHang = ngayGiaoHang;
            return hoaDon;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MaHD
        {
            get
            {
                return _MaHD;
            }
            set
            {
                if (_MaHD != value)
                {
                    OnMaHDChanging(value);
                    ReportPropertyChanging("MaHD");
                    _MaHD = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MaHD");
                    OnMaHDChanged();
                }
            }
        }
        private global::System.String _MaHD;
        partial void OnMaHDChanging(global::System.String value);
        partial void OnMaHDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MaKH
        {
            get
            {
                return _MaKH;
            }
            set
            {
                OnMaKHChanging(value);
                ReportPropertyChanging("MaKH");
                _MaKH = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MaKH");
                OnMaKHChanged();
            }
        }
        private global::System.String _MaKH;
        partial void OnMaKHChanging(global::System.String value);
        partial void OnMaKHChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MaNV
        {
            get
            {
                return _MaNV;
            }
            set
            {
                OnMaNVChanging(value);
                ReportPropertyChanging("MaNV");
                _MaNV = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaNV");
                OnMaNVChanged();
            }
        }
        private Nullable<global::System.Int32> _MaNV;
        partial void OnMaNVChanging(Nullable<global::System.Int32> value);
        partial void OnMaNVChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime NgayLapHD
        {
            get
            {
                return _NgayLapHD;
            }
            set
            {
                OnNgayLapHDChanging(value);
                ReportPropertyChanging("NgayLapHD");
                _NgayLapHD = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NgayLapHD");
                OnNgayLapHDChanged();
            }
        }
        private global::System.DateTime _NgayLapHD;
        partial void OnNgayLapHDChanging(global::System.DateTime value);
        partial void OnNgayLapHDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime NgayGiaoHang
        {
            get
            {
                return _NgayGiaoHang;
            }
            set
            {
                OnNgayGiaoHangChanging(value);
                ReportPropertyChanging("NgayGiaoHang");
                _NgayGiaoHang = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NgayGiaoHang");
                OnNgayGiaoHangChanged();
            }
        }
        private global::System.DateTime _NgayGiaoHang;
        partial void OnNgayGiaoHangChanging(global::System.DateTime value);
        partial void OnNgayGiaoHangChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QLBanHangModel", "FK_CTHD_HoaDon", "CTHD")]
        public EntityCollection<CTHD> CTHDs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CTHD>("QLBanHangModel.FK_CTHD_HoaDon", "CTHD");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CTHD>("QLBanHangModel.FK_CTHD_HoaDon", "CTHD", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QLBanHangModel", "FK_HoaDon_KhachHang", "KhachHang")]
        public KhachHang KhachHang
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<KhachHang>("QLBanHangModel.FK_HoaDon_KhachHang", "KhachHang").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<KhachHang>("QLBanHangModel.FK_HoaDon_KhachHang", "KhachHang").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<KhachHang> KhachHangReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<KhachHang>("QLBanHangModel.FK_HoaDon_KhachHang", "KhachHang");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<KhachHang>("QLBanHangModel.FK_HoaDon_KhachHang", "KhachHang", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QLBanHangModel", "FK_HoaDon_Nhanvien", "Nhanvien")]
        public Nhanvien Nhanvien
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Nhanvien>("QLBanHangModel.FK_HoaDon_Nhanvien", "Nhanvien").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Nhanvien>("QLBanHangModel.FK_HoaDon_Nhanvien", "Nhanvien").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Nhanvien> NhanvienReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Nhanvien>("QLBanHangModel.FK_HoaDon_Nhanvien", "Nhanvien");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Nhanvien>("QLBanHangModel.FK_HoaDon_Nhanvien", "Nhanvien", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QLBanHangModel", Name="KhachHang")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class KhachHang : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new KhachHang object.
        /// </summary>
        /// <param name="maKH">Initial value of the MaKH property.</param>
        public static KhachHang CreateKhachHang(global::System.String maKH)
        {
            KhachHang khachHang = new KhachHang();
            khachHang.MaKH = maKH;
            return khachHang;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MaKH
        {
            get
            {
                return _MaKH;
            }
            set
            {
                if (_MaKH != value)
                {
                    OnMaKHChanging(value);
                    ReportPropertyChanging("MaKH");
                    _MaKH = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MaKH");
                    OnMaKHChanged();
                }
            }
        }
        private global::System.String _MaKH;
        partial void OnMaKHChanging(global::System.String value);
        partial void OnMaKHChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenKH
        {
            get
            {
                return _TenKH;
            }
            set
            {
                OnTenKHChanging(value);
                ReportPropertyChanging("TenKH");
                _TenKH = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TenKH");
                OnTenKHChanged();
            }
        }
        private global::System.String _TenKH;
        partial void OnTenKHChanging(global::System.String value);
        partial void OnTenKHChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DiaChi
        {
            get
            {
                return _DiaChi;
            }
            set
            {
                OnDiaChiChanging(value);
                ReportPropertyChanging("DiaChi");
                _DiaChi = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DiaChi");
                OnDiaChiChanged();
            }
        }
        private global::System.String _DiaChi;
        partial void OnDiaChiChanging(global::System.String value);
        partial void OnDiaChiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DienThoai
        {
            get
            {
                return _DienThoai;
            }
            set
            {
                OnDienThoaiChanging(value);
                ReportPropertyChanging("DienThoai");
                _DienThoai = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DienThoai");
                OnDienThoaiChanged();
            }
        }
        private global::System.String _DienThoai;
        partial void OnDienThoaiChanging(global::System.String value);
        partial void OnDienThoaiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Fax
        {
            get
            {
                return _Fax;
            }
            set
            {
                OnFaxChanging(value);
                ReportPropertyChanging("Fax");
                _Fax = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Fax");
                OnFaxChanged();
            }
        }
        private global::System.String _Fax;
        partial void OnFaxChanging(global::System.String value);
        partial void OnFaxChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QLBanHangModel", "FK_HoaDon_KhachHang", "HoaDon")]
        public EntityCollection<HoaDon> HoaDons
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<HoaDon>("QLBanHangModel.FK_HoaDon_KhachHang", "HoaDon");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<HoaDon>("QLBanHangModel.FK_HoaDon_KhachHang", "HoaDon", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QLBanHangModel", Name="LoaiSP")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class LoaiSP : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new LoaiSP object.
        /// </summary>
        /// <param name="maLoaiSP">Initial value of the MaLoaiSP property.</param>
        public static LoaiSP CreateLoaiSP(global::System.Int32 maLoaiSP)
        {
            LoaiSP loaiSP = new LoaiSP();
            loaiSP.MaLoaiSP = maLoaiSP;
            return loaiSP;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaLoaiSP
        {
            get
            {
                return _MaLoaiSP;
            }
            set
            {
                if (_MaLoaiSP != value)
                {
                    OnMaLoaiSPChanging(value);
                    ReportPropertyChanging("MaLoaiSP");
                    _MaLoaiSP = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MaLoaiSP");
                    OnMaLoaiSPChanged();
                }
            }
        }
        private global::System.Int32 _MaLoaiSP;
        partial void OnMaLoaiSPChanging(global::System.Int32 value);
        partial void OnMaLoaiSPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenLoaiSP
        {
            get
            {
                return _TenLoaiSP;
            }
            set
            {
                OnTenLoaiSPChanging(value);
                ReportPropertyChanging("TenLoaiSP");
                _TenLoaiSP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TenLoaiSP");
                OnTenLoaiSPChanged();
            }
        }
        private global::System.String _TenLoaiSP;
        partial void OnTenLoaiSPChanging(global::System.String value);
        partial void OnTenLoaiSPChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QLBanHangModel", "FK_SanPham_LoaiSP", "SanPham")]
        public EntityCollection<SanPham> SanPhams
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SanPham>("QLBanHangModel.FK_SanPham_LoaiSP", "SanPham");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SanPham>("QLBanHangModel.FK_SanPham_LoaiSP", "SanPham", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QLBanHangModel", Name="Nhanvien")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Nhanvien : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Nhanvien object.
        /// </summary>
        /// <param name="maNV">Initial value of the MaNV property.</param>
        public static Nhanvien CreateNhanvien(global::System.Int32 maNV)
        {
            Nhanvien nhanvien = new Nhanvien();
            nhanvien.MaNV = maNV;
            return nhanvien;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaNV
        {
            get
            {
                return _MaNV;
            }
            set
            {
                if (_MaNV != value)
                {
                    OnMaNVChanging(value);
                    ReportPropertyChanging("MaNV");
                    _MaNV = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MaNV");
                    OnMaNVChanged();
                }
            }
        }
        private global::System.Int32 _MaNV;
        partial void OnMaNVChanging(global::System.Int32 value);
        partial void OnMaNVChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HoNV
        {
            get
            {
                return _HoNV;
            }
            set
            {
                OnHoNVChanging(value);
                ReportPropertyChanging("HoNV");
                _HoNV = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HoNV");
                OnHoNVChanged();
            }
        }
        private global::System.String _HoNV;
        partial void OnHoNVChanging(global::System.String value);
        partial void OnHoNVChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ten
        {
            get
            {
                return _Ten;
            }
            set
            {
                OnTenChanging(value);
                ReportPropertyChanging("Ten");
                _Ten = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ten");
                OnTenChanged();
            }
        }
        private global::System.String _Ten;
        partial void OnTenChanging(global::System.String value);
        partial void OnTenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Diachi
        {
            get
            {
                return _Diachi;
            }
            set
            {
                OnDiachiChanging(value);
                ReportPropertyChanging("Diachi");
                _Diachi = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Diachi");
                OnDiachiChanged();
            }
        }
        private global::System.String _Diachi;
        partial void OnDiachiChanging(global::System.String value);
        partial void OnDiachiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Dienthoai
        {
            get
            {
                return _Dienthoai;
            }
            set
            {
                OnDienthoaiChanging(value);
                ReportPropertyChanging("Dienthoai");
                _Dienthoai = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Dienthoai");
                OnDienthoaiChanged();
            }
        }
        private global::System.String _Dienthoai;
        partial void OnDienthoaiChanging(global::System.String value);
        partial void OnDienthoaiChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QLBanHangModel", "FK_HoaDon_Nhanvien", "HoaDon")]
        public EntityCollection<HoaDon> HoaDons
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<HoaDon>("QLBanHangModel.FK_HoaDon_Nhanvien", "HoaDon");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<HoaDon>("QLBanHangModel.FK_HoaDon_Nhanvien", "HoaDon", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QLBanHangModel", Name="SanPham")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SanPham : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SanPham object.
        /// </summary>
        /// <param name="maSP">Initial value of the MaSP property.</param>
        public static SanPham CreateSanPham(global::System.String maSP)
        {
            SanPham sanPham = new SanPham();
            sanPham.MaSP = maSP;
            return sanPham;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MaSP
        {
            get
            {
                return _MaSP;
            }
            set
            {
                if (_MaSP != value)
                {
                    OnMaSPChanging(value);
                    ReportPropertyChanging("MaSP");
                    _MaSP = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MaSP");
                    OnMaSPChanged();
                }
            }
        }
        private global::System.String _MaSP;
        partial void OnMaSPChanging(global::System.String value);
        partial void OnMaSPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenSP
        {
            get
            {
                return _TenSP;
            }
            set
            {
                OnTenSPChanging(value);
                ReportPropertyChanging("TenSP");
                _TenSP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TenSP");
                OnTenSPChanged();
            }
        }
        private global::System.String _TenSP;
        partial void OnTenSPChanging(global::System.String value);
        partial void OnTenSPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Donvitinh
        {
            get
            {
                return _Donvitinh;
            }
            set
            {
                OnDonvitinhChanging(value);
                ReportPropertyChanging("Donvitinh");
                _Donvitinh = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Donvitinh");
                OnDonvitinhChanged();
            }
        }
        private global::System.String _Donvitinh;
        partial void OnDonvitinhChanging(global::System.String value);
        partial void OnDonvitinhChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Dongia
        {
            get
            {
                return _Dongia;
            }
            set
            {
                OnDongiaChanging(value);
                ReportPropertyChanging("Dongia");
                _Dongia = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Dongia");
                OnDongiaChanged();
            }
        }
        private Nullable<global::System.Double> _Dongia;
        partial void OnDongiaChanging(Nullable<global::System.Double> value);
        partial void OnDongiaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MaLoaiSP
        {
            get
            {
                return _MaLoaiSP;
            }
            set
            {
                OnMaLoaiSPChanging(value);
                ReportPropertyChanging("MaLoaiSP");
                _MaLoaiSP = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaLoaiSP");
                OnMaLoaiSPChanged();
            }
        }
        private Nullable<global::System.Int32> _MaLoaiSP;
        partial void OnMaLoaiSPChanging(Nullable<global::System.Int32> value);
        partial void OnMaLoaiSPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HinhSP
        {
            get
            {
                return _HinhSP;
            }
            set
            {
                OnHinhSPChanging(value);
                ReportPropertyChanging("HinhSP");
                _HinhSP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HinhSP");
                OnHinhSPChanged();
            }
        }
        private global::System.String _HinhSP;
        partial void OnHinhSPChanging(global::System.String value);
        partial void OnHinhSPChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QLBanHangModel", "FK_CTHD_SanPham", "CTHD")]
        public EntityCollection<CTHD> CTHDs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CTHD>("QLBanHangModel.FK_CTHD_SanPham", "CTHD");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CTHD>("QLBanHangModel.FK_CTHD_SanPham", "CTHD", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QLBanHangModel", "FK_SanPham_LoaiSP", "LoaiSP")]
        public LoaiSP LoaiSP
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LoaiSP>("QLBanHangModel.FK_SanPham_LoaiSP", "LoaiSP").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LoaiSP>("QLBanHangModel.FK_SanPham_LoaiSP", "LoaiSP").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<LoaiSP> LoaiSPReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LoaiSP>("QLBanHangModel.FK_SanPham_LoaiSP", "LoaiSP");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<LoaiSP>("QLBanHangModel.FK_SanPham_LoaiSP", "LoaiSP", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QLBanHangModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="userName">Initial value of the UserName property.</param>
        public static User CreateUser(global::System.String userName)
        {
            User user = new User();
            user.UserName = userName;
            return user;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                if (_UserName != value)
                {
                    OnUserNameChanging(value);
                    ReportPropertyChanging("UserName");
                    _UserName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("UserName");
                    OnUserNameChanged();
                }
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();

        #endregion
    
    }

    #endregion
    
}
